# SPDX-License-Identifier: MIT
# --------------------------------------------------------------------------
# gnuradio4-core — runtime, scheduler, blocklib, meta, plugin infrastructure
# --------------------------------------------------------------------------
# Variables consumed from parent scope:
#   _EP_COMMON_ARGS, CONFIG_ENABLE_GR4_CORE, CONFIG_ENABLE_TESTING,
#   CONFIG_ENABLE_EXAMPLES, CONFIG_WARNINGS_AS_ERRORS, CONFIG_ENABLE_TBB,
#   CONFIG_ENABLE_BLOCK_REGISTRY, CONFIG_ENABLE_BLOCK_PLUGINS,
#   CONFIG_USE_FETCHCONTENT, CONFIG_ENABLE_MIT_ONLY, CONFIG_ENABLE_COVERAGE,
#   CONFIG_TIMETRACE, CONFIG_BUILD_JOBS, CONFIG_SANITIZER_ADDRESS|UB|THREAD

if(CONFIG_ENABLE_GR4_CORE)
    set(_EP_CORE_ARGS ${_EP_COMMON_ARGS})
    list(APPEND _EP_CORE_ARGS
        -DENABLE_TESTING=${CONFIG_ENABLE_TESTING}
        -DENABLE_EXAMPLES=${CONFIG_ENABLE_EXAMPLES}
        -DWARNINGS_AS_ERRORS=${CONFIG_WARNINGS_AS_ERRORS}
        -DENABLE_TBB=${CONFIG_ENABLE_TBB}
        -DGR_ENABLE_BLOCK_REGISTRY=${CONFIG_ENABLE_BLOCK_REGISTRY}
        -DINTERNAL_ENABLE_BLOCK_PLUGINS=${CONFIG_ENABLE_BLOCK_PLUGINS}
        -DGR_USE_FETCHCONTENT_DEPS=${CONFIG_USE_FETCHCONTENT}
        -DMIT_ONLY=${CONFIG_ENABLE_MIT_ONLY}
        -DENABLE_COVERAGE=${CONFIG_ENABLE_COVERAGE}
        -DTIMETRACE=${CONFIG_TIMETRACE}
        -DPARALLEL_LEVEL=${CONFIG_BUILD_JOBS}
    )
    if(CONFIG_SANITIZER_ADDRESS)
        list(APPEND _EP_CORE_ARGS -DADDRESS_SANITIZER=ON)
    endif()
    if(CONFIG_SANITIZER_UB)
        list(APPEND _EP_CORE_ARGS -DUB_SANITIZER=ON)
    endif()
    if(CONFIG_SANITIZER_THREAD)
        list(APPEND _EP_CORE_ARGS -DTHREAD_SANITIZER=ON)
    endif()

    gr4_ep(gnuradio4-core
        CMAKE_ARGS ${_EP_CORE_ARGS}
    )
endif()
